#!/bin/bash


function list_dbs {
  dbs=` ls -d */ | sed 's:/$::' `

  for db in $dbs
  do 
    echo $db;
  done
}

function create_db {
  echo "Enter Database name";
  read db_name;
  mkdir -p "$db_name"
  echo "Database created successfully";
  cd "$db_name";
}

function get_dbs_count {
  all_dbs=(*/);
  dbs_count=${#all_dbs[@]};

  if [ ! $dbs_count ]
  then
    echo "No databases found";
    exit 1;
  fi

  return $dbs_count;
}

function connect_db {
  get_dbs_count;
  dbs_count=$?;

  dbs=` ls -d */ | sed 's:/$::' `
  select db in $dbs
  do
    if [ $REPLY -gt $dbs_count ]
    then
      echo "Invalid option";
    else
      . ./db "$db";
      break;
    fi
  done
}


function drop_db {
  get_dbs_count;
  dbs_count=$?;

  dbs=` ls -d */ | sed 's:/$::' `
  select db in $dbs
  do
  if [ $REPLY -gt $dbs_count ]
  then
    echo "Invalid option";
  else
    rm -rf $db;
    break;
  fi

  done
}

# -----------------------------------
# Start Of App
echo "Welcome to DBMS App";
# main menu
select opt in "Create Database" "List Databases" "Connect to Database" "Drop Database" "Exit"
do
  case $REPLY in
  1) 
    create_db;
    ;;
  2) 
    list_dbs;
    ;;
  3) 
    connect_db;
    ;;
  4) 
    drop_db;
    ;;
  5) 
    exit 0;
    ;;
  *) 
    echo "Invalid option";
    break;
    ;;
  esac
done


